---
# file: roles/clientserver/tasks/inspec.yml
- name: Download InSpec
  get_url:
    url: "{{ inspec_download_url }}"
    dest: /var/tmp/inspec.deb
    mode: "0444"

- name: Install InSpec
  apt:
    deb: /var/tmp/inspec.deb
  become: yes
  
- name: Accept InSpec License
  become_user: ubuntu
  shell: inspec --chef-license accept
