---
- hosts: client
  become: yes
  vars:
    inspec_download_url: https://packages.chef.io/files/stable/inspec/4.22.22/ubuntu/20.04/inspec_4.22.22-1_amd64.deb
  tasks:
    - name: Download InSpec
      get_url:
        url: "{{ inspec_download_url }}"
        dest: /var/tmp/inspec.deb
        mode: "0444"
    - name: Install InSpec
      apt:
        deb: /var/tmp/inspec.deb
    - name: Accept InSpec License
      become_user: ubuntu
      shell: inspec --chef-license accept
