---
- hosts: servers
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: redirect to lab guide
      lineinfile:
        path: /etc/nginx/sites-enabled/default
        firstmatch: yes
        regexp: "try_files"
        line: "rewrite ^/$ https://f5devcentral.github.io/UDF-DevOps-Base/ redirect;"
      when: inventory_hostname == "client"
    - name: start nginx
      service:
        name: nginx
        state: started
