---
- hosts: app
  become: yes
  tasks:
    - name: Pull NGINX Demo
      docker_image:
        name: "nginxdemos/hello"
        source: pull

    - name: Create NGINX Demo
      docker_container:
        name: nginx_hello
        image: nginxdemos/hello
        state: started
        ports:
          - "8080:80"